import Link from 'next/link';
import x from '@/styles/app.module.scss';
import y from '@/styles/zit.module.scss';

export const metadata = {
  title: 'Home Page',
  description: 'Generated by create next app',
};

export default function Home() {
  return (
    <main>
      <div>
        <ul>
          <li>
            <Link href={'/facebook'} className={y['blue']}>
              <span className={y['blue']}>Facebook</span>
            </Link>
          </li>
          <li>
            <Link href={'/youtube'} className={x['red']}>
              Youtube
            </Link>
          </li>
          <li>
            <Link href={'/tiktok'} className={x['green']}>
              TikTok
            </Link>
          </li>
        </ul>
      </div>
    </main>
  );
}
