export default function ViewDefaultLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}
// export metadata
export const metadata = {
  title: `Blog`,
  description: 'Generated by create next app',
};
